sudo: false
language: node_js
node_js:
  - "9"
branches:
  only:
  - develop
  - /^greenkeeper/.*$/
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
workflows:
  version: 2
  workflow_name:
    jobs:
      - lockfile
      - job1:
          requires:
            - lockfile
install:
  - npm install
script:
  - npm run build
